# introduccion a numpy

[numpy](https://numpy.org/doc/stable/) es una biblioteca fundamental para la computacion cientifica con python.

* proporciona arrays N-dimencionales.

* Implementa funciones matematicas sofisticadas.

* proporciona herramientas para  integrar c/c++ y fortran.

* proporciona mecanismos para facilitar la realizacion de tareas relacionadas con algebra lineal o  numeros aleatorios

## imports

In [1]:
import numpy as np 

### Arrays

un **Array** es una estructura de datos que conciste en una coleccion de elementos (valores o variables) cada uno identificado por un indice o clave, un array se almacena de modo que la posicion de cada elemento se pueda calcular, a partir de su tupla de indice mediante su formula matematica. el tipo mas simple el array en un array lineal. tambien llamado unidimencional


En Numpy:

* cada dimencion se denomina **axis**.
* el numero de dimensiones se denomina **rank**.
* la lista de dimensiones con su correspondiente longitud se denomina **shape**.
* el numero total de elmentos (multiplicacion de la longitud de las dimenciones) se denomina **size**.

In [2]:
# Array con  cuyos valores son todos ceros 

a = np.zeros((2,4))

In [3]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**a** es un Array:
* con dos **axis** la primera con longitud 2 y el segundo con longitud 4
* con un **rank** igual a 2.
* con un **shape** igual (2,4)
* con un **size** igual a 8

In [4]:
a.shape

(2, 4)

In [5]:
a.ndim

2

In [6]:
a.size

8

## Creacion de arrays 

In [7]:
# array con cuyos valores son todo 0

np.zeros(((2,3,4))) #dimenciones, filas, columnas

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [8]:
## array cuyos valores son todos 1 

np.ones((2,4,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
 #arrays cuyos valores son todos el valor indicado como segundo parametro de la funcion

np.full((2,3,4),8)

array([[[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]],

       [[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]]])

In [ ]:
# el resultado de np.empty no es predecible inicializa los valores de array

np.empty((2,3,9))

array([[[4.68237570e-310, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 6.55716030e-312, 1.31607456e-292,
         1.97626258e-322, 3.17004951e-310, 6.12454250e-302],
        [4.99998019e-315, 0.00000000e+000, 6.95335581e-309,
         3.44166865e-310, 3.93720589e-302, 0.00000000e+000,
         1.00056855e-316, 5.33445445e-315, 3.60463425e-310],
        [1.99224836e+021, 0.00000000e+000, 8.89861635e-320,
         4.31613219e-316, 3.98490040e-310, 8.61952728e-288,
         3.91581293e-293, 1.12361032e-316, 7.66184714e-303]],

       [[1.57842177e+050, 0.00000000e+000, 9.65750118e-320,
         1.25216013e-312, 1.29532007e-317, 4.45014804e-308,
         3.61029760e-316, 1.53844695e-310, 0.00000000e+000],
        [0.00000000e+000, 2.41072090e+045, 0.00000000e+000,
         6.49200848e-315, 0.00000000e+000, 6.95335581e-309,
         1.05811442e-302, 1.97626258e-322, 5.64902475e-283],
        [4.17604955e-308, 5.08380774e-298, 5.56268465e-308,
         6.66070198e-315, 4.74881

In [ ]:
# inicializar un array con un array de python 

b= np.array(([1,2,3], [4,5,6]))

b

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
b.shape

(2, 3)